apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-task
spec:
  workspaces:
    - name: source
  params:
    - name: IMAGE
      type: string
      description: The full image name (e.g., quay.io/hacohen/titanic-app:latest)
  steps:
    - name: build-image
      image: quay.io/buildah/stable
      workingDir: /workspace/source/learn-OpenShift-AI
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      env:
        - name: STORAGE_DRIVER
          value: vfs
      script: |
        #!/bin/sh
        echo "Building and pushing image to $(params.IMAGE)"
        buildah --storage-driver=$STORAGE_DRIVER bud -t $(params.IMAGE) .
        buildah --storage-driver=$STORAGE_DRIVER push $(params.IMAGE)
