apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: train-task
spec:
  workspaces:
    - name: source
  steps:

    - name: run-train
      image: python:3.11
      workingDir: /workspace/source
      script: |
        echo "DEBUG: Workspace contents:"
        ls -R
        pip install --upgrade pip
        pip install --no-cache-dir pandas seaborn scikit-learn loguru
        python src/train.py