apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: train-task
spec:
  workspaces:
    - name: source
  steps:
    - name: dir-list
      image: python:3.11
      workingDir: /workspace/source
      script: |
       echo "DEBUG: Listing contents of workspace..."
       ls -R .

    - name: run-train
      image: python:3.11
      workingDir: /workspace/source
      script: |
        cd learn-OpenShift-AI
        pip install --upgrade pip
        pip install --no-cache-dir pandas seaborn scikit-learn loguru
        python src/train.py