apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: train-pipeline-run
spec:
  pipelineRef:
    name: train-pipeline
  serviceAccountName: pipeline
  params:
    - name: fallback_deploy
      value: "true"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: shared-pvc-titanic
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi